### ISSUE TITLE
scoreboard에 들어있는 팀명을 모두 영어 약자로 바꾸기

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/KBO_data#14]
`scoreboard` 모듈에서 현재 팀명을 한글로 처리하고 있습니다. 이를 영어 약자로 바꿔야 합니다.

**Comment by dev-bearabbit** [comment]
scoreboard 테이블에는 팀 ID가 들어갈 예정입니다. 다음주 월요일까지 DB 스키마가 업로드 될 예정이니 참고해주시기 바랍니다. :)
