### ISSUE TITLE
DB 스키마 문서 작성

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/KBO_data#17]
논의했던 각 DB를 따로 문서로 만들고, 이를 정리합니다.

**Comment by dialektike** [comment]
아래와 같이 하면 좋을 것 같음

```python
id = Column(Integer, primary_key=True)
    name = Column(String)
    fullname = Column(String)
    password = Column(String)
```

https://edykim.com/ko/post/getting-started-with-sqlalchemy-part-1/

**Comment by dialektike** [comment]
@choosunsick R은 문서가 작성되면 아래와 처럼 추가하면 좋을 것 같음 

```R
>    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
>   <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
```

https://db.rstudio.com/dplyr/

**Comment by dev-bearabbit** [comment]
파이썬 orm 형식으로 코드를 짜면 될까요?

**Comment by dialektike** [comment]
> 파이썬 orm 형식으로 코드를 짜면 될까요?

@Hyeonji-Ryu 우선 생각한 형식을 아래 문서에 추가해 주세요.

https://github.com/LOPES-HUFS/KBO_data/blob/main/schema/Scoreboards.md

**Comment by dev-bearabbit** [comment]
최종 스키마 결정되었습니다.
schema 폴더를 확인해주세요!
