### ISSUE TITLE
팀명에 대한 문제 해결

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/KBO_data#20]
현재 파일에 팀명을 그냥 한글로 표시하고 있습니다. 그런데 이렇게 한다면, DB 저장시에 문제가 있죠. 그래서 `TeamID`을 영어 줄임말로 해야 하는데, 이럴 때 문제가 발생합니다. 

- [ ] 영어 줄임말을 쓰면 현재 한글 팀명과 헛갈립니다.
- [ ] 영어 줄임말을 쓰면 현재 한글 팀명으로 연도별로 변환해주는 코드가 필요합니다.
- [ ] 영어 줄임말을 쓴다고 하더라도, 예전에 것을 계속 쓸지, 아니면 팀이 바뀌면 같이 바꿔 줄지 결정해야 합니다.

조금 더 논의가 필요합니다.

**Comment by dialektike** [comment]
한글로 저장시에는 아래와 같이 결국 인코딩하기 때문에 알아 보기 힘듭니다. 따라서 영어 줄임말로 하는 것이 직관적일 것 같습니다.

https://bestugi.tistory.com/16

> DBMS의 관점에서 Character Set은 문자 데이터를 저장하는 데이터 파일에 해당 문자를 어떻게 인코딩할 것인지를 지정한다. 지정된 인코딩 방식에 의해서 인코딩 된 바이너리(혹은 바이트 배열)가 데이터 파일에 최종적으로 저장 된다. 즉, UTF-8 Character Set을 사용하는 MySQL에 "한글"이라는 데이터를 Varchar 타입의 컬럼에 저장한다면, 실제 데이터 파일에는 UTF-8 인코딩 결과인 "0xED959CEAB880"이 저장될 것이다.

**Comment by dev-bearabbit** [comment]
팀 테이블은 teamID와 team name으로 구성되어 있는데 teamID는 int로 설정할 예정입니다. 만약 팀 이릉 필요하다면 팀 테이블을 조인하여 사용할 예정입니다.

**Comment by dev-bearabbit** [comment]
따라서 스코어보드의 프라이머리 키는 int로 진행해도 될 것 같습니다 :)

**Comment by dialektike** [comment]
https://www.koreabaseball.com/History/Etc/TeamHistory.aspx

윗 링크를 참고

**Comment by dialektike** [comment]
> 팀 테이블은 teamID와 team name으로 구성되어 있는데 teamID는 int로 설정할 예정입니다. 만약 팀 이릉 필요하다면 팀 테이블을 조인하여 사용할 예정입니다.

@Hyeonji-Ryu 그렇게 teamID와 team name를 int로 하면 좋지만, 실제로 분석하는 입장에서는 직관성이 떨어질 것 같네요. 고정자리 string형이 int형보다 그리 많은 용량을 차지할 것도 아니니,

**Comment by dialektike** [comment]
> 따라서 스코어보드의 프라이머리 키는 int로 진행해도 될 것 같습니다 :)

이것도 고정 문자열로 자료형을 만들면 int형보다 얼마나 더 용량을 차지할지 고민할 필요가 있을 것 같네요. 문자열로 하면 가독성이 엄청나게 향상됩니다.

**Comment by dev-bearabbit** [comment]
team name은 문자열로 들어갈 예정입니다. 말씀하시는 부분이 팀테이블에 관련된 건가요? 팀테이블 생성 여부에 대한 문제라면 다시 이슈로 올려주시기를 부탁드립니다. :)

**Comment by dev-bearabbit** [comment]
현재 팀 테이블의 예시는 다음과 같습니다.

TeamID | Team name|
|---|-----|
|01| 'SSG'|

**Comment by dev-bearabbit** [comment]
또한 batter나 pitcher에는 TeamID만 들어갈 예정입니다. 이렇게 하는 이유로는 선수 개명 이슈와 마찬가지로 차후 팀명이 변경되거나 하는 등의 상황이 올 때 빠르게 대응하기 위해서입니다.

**Comment by dialektike** [comment]
우선 파싱 단계에서는 수집한 자료만을 가지도 팀명을 저장하는 것이 좋을 것 같습니다.

**Comment by dialektike** [comment]
@Hyeonji-Ryu 은 다음과 같은 순서로 하면 될 것 같습니다.

창단 연도 순으로 배열, 같으면, 가나라순으로 배열
https://www.koreabaseball.com/About/Etc/TeamInfo.aspx

```csv
TeamID, full_name, name
1, "두산 베어스", "두산"
2, "롯데 자이언츠", "롯데"
3, "삼성 라이온즈", "삼성"
4, "한화 이글스", "한화"
5, "LG 트윈스", "LG"
6, "KIA 타이거즈", "KIA"
7, "키움 히어로즈", "키움"
8, "NC 다이노스", "NC"
9, "KT 위즈", "KT"
10, "SSG 랜더스", "SSG"
```

위와 같이 하면 앞에서 제기했던 문제가 해결될 것 같습니다.
> 
> * [x]  영어 줄임말을 쓰면 현재 한글 팀명과 헛갈립니다.
> * [x]  영어 줄임말을 쓰면 현재 한글 팀명으로 연도별로 변환해주는 코드가 필요합니다.
> * [x]  영어 줄임말을 쓴다고 하더라도, 예전에 것을 계속 쓸지, 아니면 팀이 바뀌면 같이 바꿔 줄지 결정해야 합니다.

현재 KBO 측에서도 앞의 `name` 컬럼을 단축 팀명으로 사용하고 있습니다.

**Comment by dialektike** [comment]
문제는 또 있는데, 과거 팀, 예를 들어 SK와 같은 팀은 어떻게 처리할 것인지 고민중입니다.

**Comment by dialektike** [comment]
> https://www.koreabaseball.com/History/Etc/TeamHistory.aspx
> 
> 윗 링크를 참고

아래 링크를 참고하면 KBO 자료가 2001년 4월부터 있습니다.

https://www.koreabaseball.com/Schedule/GameCenter/Main.aspx

결과적으로 2000년에 SK, 2001년에 KIA가 창단되었으니, 그 전에 사라진 구단 ID는 필요없을 것 같습니다. 그러니 SK만 추가하여 `TeamID`아래와 같이 11개를 만들면 될 것 같습니다.

```ini
[TEAM]
두산: 1
롯데: 2
삼성: 3
한화: 4
LG: 5
KIA: 6
SK: 7
키움: 8
NC: 9
KT: 10
SSG: 11
```

**Comment by dialektike** [comment]
어느 정도 정리된 것 같아서 아래 문서를 시작했습니다. 구단 이름에 관련된 것이 있으면, 아래 링크를 수정해주세요.

https://github.com/LOPES-HUFS/KBO_data/wiki/구단-이름에-대한-문제점

그리고 TeamID 관련된 것들은 다음 것을 참고해서 하시면 될 것 같습니다.

a7945ac9d858b4e1dc8e8f7260e7d78ff335b6c7
