### ISSUE TITLE
DB 스키마 열 설명 정리

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/KBO_data#22]
[`DB 스키마 열 설명.md`](https://github.com/LOPES-HUFS/KBO_data/blob/main/schema/DB%20스키마%20열%20설명.md) 내용을 [`Scoreboards.md`](https://github.com/LOPES-HUFS/KBO_data/blob/main/schema/Scoreboards.md)와 같이 아래 파일을 참고하여 각각의 파일로 만든 다음, [`Scoreboards.md`](https://github.com/LOPES-HUFS/KBO_data/blob/main/schema/Scoreboards.md)과 같은 형식으로 정리한 다음, [`DB 스키마 열 설명.md`](https://github.com/LOPES-HUFS/KBO_data/blob/main/schema/DB%20스키마%20열%20설명.md) 파일을 제거해주세요. 참고로 파일 이름은 **영어로** 부탁드립니다. ^^;

https://github.com/LOPES-HUFS/KBO_data/blob/main/schema/tables.md

**Comment by choosunsick** [comment]
@dialektike 열 설명 파일 제거 했습니다. 이후 다른 테이블들도 Scoreboards.md 와 같은 형식으로 만들겠습니다
