### ISSUE TITLE
KBO 경기 스케줄 모으기

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/KBO_data#29]
2001년부터 2008년까지 정규시즌 KBO 경기 스케줄을 모읍니다.

**Comment by choosunsick** [comment]
@dialektike 2008년까지 스케쥴 다 모으고 년도별로 전경기 다 있는것 확인했습니다.

**Comment by dialektike** [comment]
@choosunsick `temp_schedule_2017.csv`과 같은 형식으로 `KBO_data/sample_data/`에 연도별로 넣어주세요.

**Comment by dialektike** [comment]
@choosunsick

bbf96c245a84c5f456e45764bcaf6bc069c363b3
