### ISSUE TITLE
KBO 경기 자료 모으기

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/KBO_data#31]
예전 자료를 보완하기 위해서 자료를 다시 모읍니다.

- [x] 2020년
- [x] 2019년
- [x] 2018년
- [x] 2017년
- [x] 2016년
- [x] 2015년
- [x] 2014년
- [x] 2013년
- [x] 2012년
- [x] 2011년
- [x] 2010년
- [x] 2009년
- [x] 2008년
- [x] 2007년
- [x] 2006년
- [x] 2005년
- [x] 2004년
- [x] 2003년
- [x] 2002년
- [x] 2001년

**Comment by dialektike** [comment]
2020 년 완료
7755b36c98b757f50e3139873509b152ca7954fb

**Comment by dialektike** [comment]
2019 년 완료
1105ad5a9eb121ad10ae649d3a96b3fc246e13bc

**Comment by dev-bearabbit** [comment]
2017년부터 모으면 되는건가요?

**Comment by dialektike** [comment]
@Hyeonji-Ryu 2008년부터 하시면 됩니다.

**Comment by dialektike** [comment]
2017년 완료

7f55498905cabb2da00c1c49fc81c38825739620

**Comment by dialektike** [comment]
@choosunsick 2001년부터 모아주세요!

**Comment by choosunsick** [comment]
@dialektike 현재 크롤링은 parsing page 하고 get_data 안의 함수로 이루어지고 있나요?

**Comment by dialektike** [comment]
2016년 완료

4a627ee4f9dfb84a9ee450786ed95fb6d2edb604

**Comment by dialektike** [comment]
@choosunsick 다음 링크 참고하세요.
https://github.com/LOPES-HUFS/KBO_data/blob/4a627ee4f9dfb84a9ee450786ed95fb6d2edb604/kbo_data/utility.py#L79

**Comment by dialektike** [comment]
2014년 완료

7a39b62723747d3a5da2275740ca670f34aa0008

**Comment by dialektike** [comment]
2013년 완료

963dda53806beb26441533f5e060d06b52831774

**Comment by dialektike** [comment]
2012년 완료

f9bd6b89514d479b164e0a138f319f0bd500019a

**Comment by dialektike** [comment]
2011년 완료

7bed79ac8479ab27b9ac91f2391a5984eaf3d5e6

**Comment by dialektike** [comment]
2010년 완료

e08729458f0bf096e209709ce5db69b01ef162f0

**Comment by dialektike** [comment]
2009년 완료

4e22869971c6fe15548d53afc6fdf4778b09792f

**Comment by dialektike** [comment]
2008년 완료

c1ba64056d0491e59fb7aaa57a76034fc98a29b8

**Comment by dialektike** [comment]
2015년, 2018년 일단 완료

45425ebc4f368ef8c02e2a756a7f27b7ea5be2b6

아래 경기만 넣으면 됩니다.

```csv
20150708,HTWO0
20180801,WOSK0
```

**Comment by dialektike** [comment]
자료 모으는 것은 완료했습니다.

누락된 자료를 모으는 것은 다음 이슈로...

https://github.com/LOPES-HUFS/KBO_data/issues/35
