### ISSUE TITLE
수집한 자료에서 스코어보드 자료를 `csv`형식으로 만들기

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/KBO_data#33]

**Comment by dev-bearabbit** [comment]
parquet말고 csv로 하나요?

**Comment by dialektike** [comment]
@Hyeonji-Ryu  Github에 저장할 수 있는 파일 용량이 100MB 까지 입니다. 지금까지 수집한 전체 스코어보드 자료를 csv format으로 작업했을 때, 이 용량보다 작은지 큰지 확인하려고 우선 csv으로 작업하는 것입니다. 이보다 크면 parquet format으로 작업할 것입니다.

**Comment by dialektike** [comment]
@Hyeonji-Ryu 참고로 다른 자료들은 csv format으로 작업하면, 파일 용량이 100MB 을 넘길 것 같네요.

**Comment by dialektike** [comment]
b18b651
