### ISSUE TITLE
선수 관련 모듈 이전 요청

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/KBO_data#4]
https://github.com/LOPES-HUFS/KBO_data/tree/main/player_id 에 작성한 작성한 모듈을 https://github.com/LOPES-HUFS/KBO_data/blob/main/kbo_data/get_players.py 으로 이전해 주세요. 나중에 피키지를 만들기 위해서는 특정 폴더에 모듈이 다 들어야 하기 때문입니다.

**Comment by dev-bearabbit** [comment]
모듈 이전 완료했습니다 :)
