### ISSUE TITLE
자료 구조를 12회 이상 연장전을 처리할 수 있게 수정

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/KBO_data#40]
현재 우리가 사용하고자 하는 자료 구조로는 12회 이상 경기 자료를 처리할 수 없습니다. 이를 해결하기 위해 자료 구조를 변경해야 합니다.

**Comment by dev-bearabbit** [comment]
확인 결과 과거데이터에서 최대 18회 연장 경기가 있습니다. 이에 2가지의 방법을 제안합니다.

1. 현재 스키마에서 i_18까지의 column 생성
2. i_1 ~i_18까지의 데이터를 쉼표로 구분한 하나의 문자열로 column에 적재

이 중에 어떤 방법이 좋은지에 대한 답변 부탁드립니다 :)

**Comment by dev-bearabbit** [comment]
회의 결과 1번 방법을 택하기로 결정되었습니다 :)
