### ISSUE TITLE
DB에 올린 자료를 업그레이드 하는 코드 구현

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/KBO_data#48]
현재 자료를 올리는 것만 구현되어 있습니다. 그래서 이미 입력된 같은 자료를 입력하면 다음과 같은 에러가 나옵니다.

```python
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '20210811011' for key 'PRIMARY'")
```

그러나 자료를 수정할 때도 있고, 반복해서 입력하는 경우도 있습니다.
이것을 구현할 필요가 있습니다. 아래 관련 링크

https://docs.sqlalchemy.org/en/14/core/tutorial.html#inserts-updates-and-deletes

**Comment by dev-bearabbit** [comment]
해결 완료
