### ISSUE TITLE
스케쥴 자료에 중복 자료 존재 문제 발생

### ISSUE THREAD

**Issue by choosunsick** [LOPES-HUFS/KBO_data#49]
2019년 스케쥴 자료 7월이 두번 들어가고 6월이 존재하지 않음
2009년 2020년 스케쥴 중복 자료 문제는 해결완료

**Comment by choosunsick** [comment]
2009년, 2019년, 2020년 json 자료 재 다운로드 필요

**Comment by dialektike** [comment]
@choosunsick 다른 자료는 문제없나요?

**Comment by choosunsick** [comment]
> @dialektike 
15년 18년 각각 1경기씩 홈페이지 문제로 자료 없는것 이외에 홈페이지 화면은 뜨지만 데이터가 없는 경우가 2010년 이전 년도에 종종 있습니다. 예를 들면 2009년 4월4일 롯데와 히어로즈 경기의 자료가 그렇습니다.

**Comment by dialektike** [comment]
> 2009년, 2019년, 2020년 json 자료 재 다운로드 필요

@choosunsick 완료

**Comment by dialektike** [comment]
줌복 자료를 가지고 있는 자료는 모두 다 새로 받아서 수정했습니다.

그리고 자료를 수집 못하는 경기는 아래 파일에 별로도 정리하여 따로 모으도록 할 예정입니다.

https://github.com/LOPES-HUFS/KBO_data/blob/main/kbo_data/kbo_data.ini
