### ISSUE TITLE
Job 작동 시 일부만 크롤링 되는 현상

### ISSUE THREAD

**Issue by dev-bearabbit** [LOPES-HUFS/KBO_data#59]
데이터를 가져오는 get_data Job이 일부데이터만 크롤링 해오는 현상이 발생합니다.
가져오지 못하는 경우 에러는 다음과 같습니다.

```
list index out of range
finally...
'NoneType' object is not subscriptable
```

**Comment by dialektike** [comment]
@Hyeonji-Ryu 아래와 같은 수정으로 이 문제로 해결될 것 같습니다.

https://github.com/LOPES-HUFS/KBO_data/commit/c13c35fee86464b7db4c9abddb8c92532ed4cbdc

최근 action에서 일어나는 문제는 DB 중복 문제 때문에 에러가 발생하고 있습니다. 아래 링크 참고해주세요.

https://github.com/LOPES-HUFS/KBO_data/runs/4403466485?check_suite_focus=true
