### ISSUE TITLE
batters 데이터 구조 정리하기

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/KBO_data#67]
현재 정해져 있는 batters 데이터 구조가 명확하지 않습니다. 이를 명확하게 정해서 아래 문서를 통해 제시합니다. 

https://github.com/LOPES-HUFS/KBO_data/blob/main/schema/Batters.md

그런 다음 이를  `batters.output()`에 적용합니다. 아래 링크 참고

https://github.com/LOPES-HUFS/KBO_data/blob/0c5101addebb927e101130ed69150a240c7284b2/kbo_data/batters.py#L147

**Comment by dev-bearabbit** [comment]
완료!
