### ISSUE TITLE
pitchers 데이터 구조 정리하기

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/KBO_data#68]
현재 정해져 있는 pitchers 데이터 구조가 명확하지 않습니다. 이를 명확하게 정해서 아래 문서를 통해 제시합니다.

https://github.com/LOPES-HUFS/KBO_data/blob/main/schema/Pitchers.md

그런 다음 이를 pitchers.output()에 적용합니다. 아래 링크 참고

https://github.com/LOPES-HUFS/KBO_data/blob/53c49707fcfd6f9235edfa8298b7bddad0a3121d/kbo_data/pitchers.py#L74

**Comment by dev-bearabbit** [comment]
완료!
